routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/', 'PageController@home')->name('home');
Route::get('/contact', 'PageController@contact')->name('contact');
Route::get('/cookies-policy', 'PageController@cookies_policy')->name('cookies.policy');

Route::middleware(['auth'])->group(function () {
	Route::prefix('dashboard')->group(function () {
		Route::get('/', 'DashboardController@index')->name('dashboard');
		Route::post('/rolemenu/delete', 'RoleMenuController@delete')->name('role-menu.delete');
		Route::resources([
			'configuration'=>'ConfigurationController',
			'user'=>'UserController',
			'menu'=>'MenuController',
			'role'=>'RoleController',
			'role-menu'=>'RoleMenuController',
		]);
	});
});

app/Http/Controllers/ConfigurationController.php
<?php

namespace App\Http\Controllers;

use App\Http\Models\Configuration;
use Illuminate\Http\Request;

class ConfigurationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('building');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('building');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        return view('building');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Http\Models\Configuration  $configuration
     * @return \Illuminate\Http\Response
     */
    public function show(Configuration $configuration)
    {
        //
        return view('building');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Http\Models\Configuration  $configuration
     * @return \Illuminate\Http\Response
     */
    public function edit(Configuration $configuration)
    {
        //
        return view('configuration.edit', compact('configuration'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Http\Models\Configuration  $configuration
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Configuration $configuration)
    {
        //

        Configuration::find($configuration->id)->update($request->all());
        return redirect()->route('configuration.index')->with('message','Configuración actualizada satisfactoriamente.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Http\Models\Configuration  $configuration
     * @return \Illuminate\Http\Response
     */
    public function destroy(Configuration $configuration)
    {
        //
        return view('building');
    }
}

resources/views/configuration/edit.blade.php
@extends('layouts.dashboard')

@section('dashboard-content')   
<div class="row">
    <div class="col s12 m12 l12">
        <nav class="blue darken-3">
            <div class="nav-wrapper">
              <div class="col s12 m12 l12">
                <a href="{{route('dashboard')}}" class="breadcrumb">Panel de control</a>
                <a href="{{route('configuration.index')}}" class="breadcrumb">Configuración</a>
                <a href="#!" class="breadcrumb">Editar</a>
              </div>
            </div>
        </nav>
    </div>
    <div class="col  s12 m12 l12">
        <h4 class="center-align">Editar categoria</h4>

      {!! Form::model($configuration, ['method' => 'PATCH','route' => ['configuration.update', $configuration->id], 'class'=>'col s12', 'enctype'=>"multipart/form-data",]) !!}
        @include('configuration.form')

    {!! Form::close() !!}
    </div>
</div>
@endsection
@section('scripts')
    <script type="text/javascript">
        $(function () {
            $.each($('.wysiwyg'), function(index, node) {
            $(node).materialnote({
                height: 300,
                posIndex: index
            });
        });
        })
    </script>
@stop

resources/views/configuration/form.blade.php
<div class="row">
  <div class="input-field col s12">
    {!! Form::text('key', null, array('id' => 'key', 'readonly', 'disable')) !!}
    <label for="key">Nombre</label>
  </div>
  <div class="input-field col s12">
    <h4 for="key_value">Valor</h4>
    {!! Form::textarea('key_value', null, array('class' => 'wysiwyg hide', 'data-wysiwyg'=>'materialnote', 'id' => 'key_value')) !!}
  </div>
  <div class="input-field col s12">
    <h4 for="key_description">Descripcion</h4>
    {!! Form::textarea('key_description', null, array('class' => 'wysiwyg hide', 'data-wysiwyg'=>'materialnote', 'id' => 'key_description')) !!}
  </div>
</div>
<div class="row">
  <div class="input-field col s12">
    <button class="btn red waves-effect waves-light" type="submit" name="action">Guardar
      <i class="mdi-save right"></i>
    </button>
  </div>
</div>

resources/views/configuration/index.blade.php
@extends('layouts.dashboard')

@section('dashboard-content')   
<div class="row">
    <div class="col s12 m12 l12">
        <nav class="blue darken-3">
            <div class="nav-wrapper">
              <div class="col s12 m12 l12">
                <a href="{{route('dashboard')}}" class="breadcrumb">Panel de control</a>
                <a href="#!" class="breadcrumb">Configuración</a>
              </div>
            </div>
        </nav>
    </div>
    <div class="col  s12 m12 l12">
        <h4 class="center-align">Configuraciones registradas</h4>
        <table class="striped highlight responsive-table">
            <tr>
                <th>No</th>
                <th>Nombre</th>
                <th>Acciones</th>
            </tr>
            @foreach ($configurations as $configuration)
                <tr>
                    <td>{{ $configuration->id }}</td>
                    <td>
                            {{ $configuration->key}}
                    </td>
                    <td>
                        <a class="btn waves-effect waves-light " href="{{ route('configuration.show',$configuration->id) }}"><i class="material-icons">remove_red_eye</i></a>
                        <a class="btn waves-effect waves-light " href="{{ route('configuration.edit',$configuration->id) }}"><i class="material-icons">edit</i></a>
                    </td>
                </tr>
            @endforeach
        </table>
    </div>
</div>
@endsection