routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/', 'PageController@home')->name('home');
Route::get('/contact', 'PageController@contact')->name('contact');
Route::get('/cookies-policy', 'PageController@cookies_policy')->name('cookies.policy');

Route::middleware(['auth'])->group(function () {
	Route::prefix('dashboard')->group(function () {
		Route::get('/', 'DashboardController@index')->name('dashboard');
		Route::post('/rolemenu/delete', 'RoleMenuController@delete')->name('role-menu.delete');
		Route::resources([
			'configuration'=>'ConfigurationController',
			'user'=>'UserController',
			'menu'=>'MenuController',
			'role'=>'RoleController',
			'role-menu'=>'RoleMenuController',
		]);
	});
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" href="{{asset('img/favicon.png?v=1')}}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles --> 
    @if(config('app.env', 'production')=='local') 
      <link href="{{ asset('css/icon.css') }}" rel="stylesheet">
      <link href="{{ asset('css/materialize.min.css') }}" rel="stylesheet">
    @else
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    @endif
    <link href="{{ asset('css/custom.css?v='.date('is')) }}" rel="stylesheet">

    
</head>
<body>
    <header>
      <nav class="blue darken-3">
          <div class="container">
              <div class="nav-wrapper">
                <a class="brand-logo" href="{{ url('/') }}">
                  {{ config('app.name', 'Laravel') }}
                </a>
                <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
                <ul class="right hide-on-med-and-down">
                  @guest
                      <li  class="{{Route::currentRouteName()=='login'?'active':''}}"><a href="{{ route('login') }}">Iniciar sesión</a></li>
                      <li  class="{{Route::currentRouteName()=='register'?'active':''}}"><a href="{{ route('register') }}">Registrar</a></li>
                  @else
                  @endguest
                </ul>
                <ul class="side-nav" id="mobile-demo">
                  <!-- Authentication Links -->
                  @guest
                      <li  class="{{Route::currentRouteName()=='login'?'active':''}}"><a href="{{ route('login') }}">Iniciar sesión</a></li>
                      <li  class="{{Route::currentRouteName()=='register'?'active':''}}"><a href="{{ route('register') }}">Registrar</a></li>
                  @else   
                      @include('layouts.menu')                  
                  @endguest
                </ul>
              </div>
          </div>
      </nav>
    </header>
    <main id="app">
        @yield('content')
    </main>

    <footer class="page-footer" style="padding-top: 0px;">
      <!-- <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">Footer Content</h5>
            <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Links</h5>
            <ul>
              <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
            </ul>
          </div>
        </div>
      </div> -->
      <div class="footer-copyright blue darken-3">
        <div class="container">
        Copyright 2018 <a href="http://elduke.com.ve/" target="_blank" class="white-text bold">El Duke</a> | Todos los Derechos Reservados | <a href="{{route('cookies.policy')}}" class="white-text bold">Política de Cookies</a>
        </div>
      </div>
    </footer>
    <!-- Scripts -->
    @if(config('app.env', 'production')=='local') 
      <script src="{{ asset('js/jquery-3.3.1.min.js') }}"></script>
      <script src="{{ asset('js/materialize.min.js') }}"></script>
    @else
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    @endif
    <script src="{{ asset('js/custom.js?v='.date('is')) }}"></script>
</body>
</html>

resources/views/layouts/dashboard.blade.php
 <!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{{asset('img/favicon.png?v=1')}}">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->  
    @if(config('app.env', 'production')=='local')
      <link href="{{ asset('css/icon.css') }}" rel="stylesheet">
      <link href="{{ asset('css/materialize.min.css') }}" rel="stylesheet">
    @else
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    @endif
    <link href="{{asset('css/materialnote.css')}}" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/custom.css?v='.date('is')) }}" rel="stylesheet">

    
</head>
<body class="dashboard">
    <header>
      <div class="message hide">{{session('message')}}</div>
      <div class="message-error hide">@if ($errors->count())<div class="yellow-text lighten-4"><ul>@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif</div>
      <nav class="blue darken-3  show-on-small hide-on-med-and-up">
          <div class="container">
              <div class="nav-wrapper">
                <a class="brand-logo show-on-small hide-on-med-and-up" href="{{ url('/') }}">
                  {{ config('app.name', 'Laravel') }}
                </a>
                <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
                
             {{--<ul id="nav-mobile" class="right">
                  <li><a href="collapsible.html"><i class="material-icons">notifications</i></a></li>
                </ul> --}}
                <ul class="side-nav" id="mobile-demo">
                  @guest
                      <li  class="{{Route::currentRouteName()=='login'?'active':''}}"><a href="{{ route('login') }}">Iniciar sesión</a></li>
                      <li  class="{{Route::currentRouteName()=='register'?'active':''}}"><a href="{{ route('register') }}">Registrar</a></li>
                  @else   
                      @include('layouts.menu')                  
                  @endguest
                </ul>
              </div>
          </div>
      </nav>
    </header>
    <main id="app">
      <div class="row">
        <div class="col m2 l2 hide-on-small-only">
          <div class="side-nav fixed">
            <ul class="collection nav-side" style="">
              @include('layouts.menu')
            </ul>
          </div>
        </div>
        <div class="col s12 m12 l12" >
          <div class="main">
            <br>
            @yield('dashboard-content')
          </div>
        </div>
      </div>

      <div class="fixed-action-btn">
        <a class="btn-floating btn-large light-blue darken-3 pulse">
          <i class="large material-icons">add</i>
        </a>
        <ul>


         <li><a href="#!" onclick="print()" class="btn-floating green tooltipped" data-position="left" data-delay="50" data-tooltip="Imprimir"><i class="material-icons">print</i></a></li>
          @if(Auth::user()->role->slug=='admin')
           <li><a href="{{route('configuration.create')}}" class="btn-floating deep-purple darken-1 tooltipped" data-position="left" data-delay="50" data-tooltip="Configuración"><i class="material-icons">settings</i></a></li>
           @endif
        </ul>
      </div>
  </main>
    @if(config('app.env', 'production')=='local') 
      <script src="{{ asset('js/jquery-3.3.1.min.js') }}"></script>
      <script src="{{ asset('js/materialize.min.js') }}"></script>
    @else
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    @endif
    <script type="text/javascript" src="{{asset('js/materialnote.js')}}"></script>  
    <script src="{{ asset('js/custom.js?v='.date('is')) }}"></script>
    @section('scripts')
    @show
</body>
</html>

resources/views/layouts/index.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" href="{{asset('img/favicon.png?v=1')}}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->  
    @if(config('app.env', 'production')=='local') 
      <link href="{{ asset('css/icon.css') }}" rel="stylesheet">
      <link href="{{ asset('css/materialize.min.css') }}" rel="stylesheet">
    @else
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    @endif
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js" integrity="sha384-SlE991lGASHoBfWbelyBPLsUlwY1GwNDJo3jSJO04KZ33K2bwfV9YBauFfnzvynJ" crossorigin="anonymous"></script>
    <link href="{{ asset('css/custom.css?v='.date('is')) }}" rel="stylesheet">
     
    <!-- Include js plugin -->
</head>
<body  class="{{Route::currentRouteName()}}">
  <div class="loader hide">
    
    <div class="preloader-wrapper big active">
      <div class="spinner-layer spinner-blue">
        <div class="circle-clipper left">
          <div class="circle"></div>
        </div><div class="gap-patch">
          <div class="circle"></div>
        </div><div class="circle-clipper right">
          <div class="circle"></div>
        </div>
      </div>

      <div class="spinner-layer spinner-red">
        <div class="circle-clipper left">
          <div class="circle"></div>
        </div><div class="gap-patch">
          <div class="circle"></div>
        </div><div class="circle-clipper right">
          <div class="circle"></div>
        </div>
      </div>

      <div class="spinner-layer spinner-yellow">
        <div class="circle-clipper left">
          <div class="circle"></div>
        </div><div class="gap-patch">
          <div class="circle"></div>
        </div><div class="circle-clipper right">
          <div class="circle"></div>
        </div>
      </div>

      <div class="spinner-layer spinner-green">
        <div class="circle-clipper left">
          <div class="circle"></div>
        </div><div class="gap-patch">
          <div class="circle"></div>
        </div><div class="circle-clipper right">
          <div class="circle"></div>
        </div>
      </div>
    </div>
        
  </div>
    <header class="navbar-fixed" style="height: 80;">
      <div class="message hide">{{session('message')}}</div>
      <nav class="blue darken-3">
          <div class="container">
              <div class="nav-wrapper">
                <a class="brand-logo" href="{{ url('/') }}">
                  {{-- <img src="{{asset('img/logo.png')}}" class="responsive-img logo" alt="Logo"> --}}
                  {{ config('app.name', 'Laravel') }}
                </a>
                <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
                <ul class="right hide-on-med-and-down">
                  @guest
                      <li  class="{{Route::currentRouteName()=='login'?'active':''}}"><a href="{{ route('login') }}">Iniciar sesión</a></li>
                      <li  class="{{Route::currentRouteName()=='register'?'active':''}}"><a href="{{ route('register') }}">Registrar</a></li>
                  @else
                  @endguest
                </ul>
                <ul class="side-nav" id="mobile-demo">
                  @guest
                      <li  class="{{Route::currentRouteName()=='login'?'active':''}}"><a href="{{ route('login') }}">Iniciar sesión</a></li>
                      <li  class="{{Route::currentRouteName()=='register'?'active':''}}"><a href="{{ route('register') }}">Registrar</a></li> 
                  @else
                  @endguest
                  
                </div>
          </div>
      </nav>
    </header>
    <main id="app">
        @yield('content')
    </main>
<footer class="page-footer blue accent-4" style="padding-top: 0px;">
      <div class="container">
        <div class="row">
          <div class="col s12 m4"></div>
          <div class="col s12 m4"></div>
          <div class="col s12 m4"></div>
        </div>
      </div>
      <div class="footer-copyright blue accent-4">
        <div class="container">
        Copyright 2018 <a href="http://elduke.com.ve/" target="_blank" class="white-text bold">El Duke</a> | Todos los Derechos Reservados | <a href="{{route('cookies.policy')}}" class="white-text bold">Política de Cookies</a>
        </div>
      </div>
    </footer>
    <div class="cookies-policy white">
      <div class="">
        <div class="row center-align" style="margin-bottom: 0px;">
          En cumplimiento con la Ley 34/2002 de servicios de la sociedad de la información te recordamos que al navegar por este sitio estás aceptando el uso de cookies. <a href="#" class="btn black done">Aceptar</a> <a href="{{route('cookies.policy')}}" class="black-text bold">Leer Más</a>
          
        </div>
      </div>
    </div>
    <!-- Scripts -->
    @if(config('app.env', 'production')=='local') 
      <script src="{{ asset('js/jquery-3.3.1.min.js') }}"></script>
      <script src="{{ asset('js/materialize.min.js') }}"></script>
    @else
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    @endif

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    <script src="{{ asset('js/custom.js?v='.date('is')) }}"></script>
    <script>
      $(function () {
        // body...

        if ($.cookie("cookies-policy")==1) {
          $('.cookies-policy').remove();
        }
        $('.cookies-policy a.done').click(function (e) {
          $.cookie("cookies-policy", 1, {expires : 15});
          $('.cookies-policy').remove();
          e.preventDefault();
        });
      });
    </script>
  @section('scripts')
  @show
</body>
</html>

resources/views/layouts/menu.blade.php
	<li class="collection-item  hide-on-small-only show-on-medium-and-up" style="height: 90px;"><a href="{{ route('home') }}">{{-- <img src="{{asset('img/logo.png')}}" class="responsive-img logo" alt="Logo"> --}} <h4> {{ config('app.name', 'Laravel') }}</h4></a></li>
	@foreach(Auth::user()->role->menu()->orderBy('position','asc')->get() as $menu)
		<li class="collection-item {{Route::currentRouteName()==$menu->route?'active blue darken-3 white-text':''}}">
			<a href="{{route($menu->route)}}" class="{{Route::currentRouteName()==$menu->route?'active blue darken-3 white-text':''}}"><i class="material-icons circle {{Route::currentRouteName()==$menu->route?'active blue darken-3 white-text':''}}">{{$menu->ico}}</i>
				<span class="title">
                    @if($menu->route=='order.index')
                        @if(Auth::user()->warehouse->orders()->where('status', 1)->count())
                            <span class="badge new blue material-icons" data-badge-caption="local_shipping"></span>
                        @endif
                        @if(Auth::user()->warehouse->order()->where('status', 2)->count())
                            <span class="badge new red material-icons" data-badge-caption="check"></span>
                        @endif
                    @endif
                    {{$menu->name}}
                </span>
			</a>
		</li>
	@endforeach
    <li class="collection-item">
        <a href="{{ route('logout') }}"
            onclick="event.preventDefault();
                     document.getElementById('logout-form').submit();">
            <i class="material-icons">do_not_disturb_on</i>  Cerrar sesión
        </a>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            {{ csrf_field() }}
        </form>
    </li>  